version: '2.1'

services:
  binary1:
    build:
      context: .
    image: pwn
    container_name: slashroot7-baru-belajar
    entrypoint: socat tcp listen:8000, reuseaddr, fork exec:/home/app/chall
    volumes: 
      - '.:/home/app'
    ports:
      - '2022:8080'
